#!/sbin/sh

export BOOTREC_CACHE_NODE="/dev/block/mtdblock3 b 31 3"
export BOOTREC_CACHE="/dev/block/mtdblock3"
export BOOTREC_EVENT_NODE="/dev/input/event7 c 13 71"
export BOOTREC_EVENT="/dev/input/event7"
export BOOTREC_LED_RED="/sys/class/leds/red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/blue/brightness"

